version: '3.7'
services:
  db:
    image: postgres:latest
    container_name: compose-tcc-monolito-postgres
    environment:
      POSTGRES_PASSWORD: monolito
      POSTGRES_USER: monolito
      POSTGRES_DB: monolito
    ports:
      - '5432:5432'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
  app:
    build: './app'
    container_name: compose-tcc-monolito-java
    environment:
      spring.profiles.active: test
    ports:
      - '8080:8080'
      - '9999:9999'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
    depends_on:
      - db
